<%@ Page Title="" Language="C#" MasterPageFile="~/Interfaces/Site.Master" AutoEventWireup="true" CodeBehind="formConsultaTemas.aspx.cs" Inherits="Proyecto_Ingles_V2.Interfaces.ConsultaTemas" async="true"%>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <div class="container" >
<h4 class="well" style="background-color:rgb(8, 83, 148);color:white;text-align:center">Consulta Temas Nivel</h4>
	<div class="col-lg-12 well">
	<div class="row">
        <div class="col-sm-12">
                   <div class="form-group">                                
                         <asp:Label ID="Label2" runat="server" Text="Nivel"></asp:Label>
                         <asp:DropDownList ID="ddlNivel" AppendDataBoundItems="true" runat="server" AutoPostBack="true" class="form-control" OnSelectedIndexChanged="ddlNivel_SelectedIndexChanged">                               
                         <asp:ListItem Text="--seleccionar--" Value="0" />
                         </asp:DropDownList>                               
                   </div>    
            <div class="container" style="padding-left:5%;padding-right:2%;">                
                <div class="row">
                    <div class="col-md-10">
            <div class="table-responsive">
            <asp:GridView ID="dgvNivel" runat="server"  CellPadding="4" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" AutoGenerateColumns="False"   CaptionAlign="Bottom" AutoGenerateDeleteButton="True"  EnablePersistedSelection="True" Width="635px"  >
                <Columns>
                    <asp:BoundField DataField="IdNomUnidad" HeaderText="Id" SortExpression="IdNomUnidad" />
                    <asp:BoundField DataField="IdNivel" HeaderText="Nivel" SortExpression="IdNivel"/>
                    <asp:BoundField DataField="NomUnidad" HeaderText="Tema" SortExpression="NomUnidad" />
                </Columns>
                <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                <HeaderStyle BackColor="#085394" Font-Bold="True" ForeColor="#CCCCFF" />
                <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                <RowStyle BackColor="White" ForeColor="#003399" />
                <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                <SortedAscendingCellStyle BackColor="#EDF6F6" />
                <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                <SortedDescendingCellStyle BackColor="#D6DFDF" />
                <SortedDescendingHeaderStyle BackColor="#002876" />
                </asp:GridView>
                </div>
                </div>
            </div>
            </div>

        </div>
        </div>
        </div>
    </div>
</asp:Content>
